const GLOBAL_PAGE = 'ALERT'

export const SET_ALERT_MESSAGE_WITH_ICON = `${GLOBAL_PAGE}_SET_ALERT_MESSAGE_WITH_ICON`
export const SET_ALERT_MESSAGE_WITH_ICON_WITHOUT_TRANSLATE = `${GLOBAL_PAGE}_SET_ALERT_MESSAGE_WITH_ICON_WITHOUT_TRANSLATE`
export const SET_SUCCESS_ALERT_MESSAGE_WITH_ICON = `${GLOBAL_PAGE}_SET_SUCCESS_ALERT_MESSAGE_WITH_ICON`
export const SET_ERROR_ALERT_MESSAGE_WITH_ICON = `${GLOBAL_PAGE}_SET_ERROR_ALERT_MESSAGE_WITH_ICON`
export const SET_WARNING_ALERT_MESSAGE_WITH_ICON = `${GLOBAL_PAGE}_SET_WARNING_ALERT_MESSAGE_WITH_ICON`
export const SET_GLOBAL_ERROR_ALERT_MESSAGE_WITH_ICON = `${GLOBAL_PAGE}_SET_GLOBAL_ERROR_ALERT_MESSAGE_WITH_ICON`
export const SET_CUSTOM_GLOBAL_ERROR_ALERT_MESSAGE_WITH_ICON = `${GLOBAL_PAGE}_SET_CUSTOM_GLOBAL_ERROR_ALERT_MESSAGE_WITH_ICON`
export const CLOSE_SUCCESS_ALERT = `${GLOBAL_PAGE}_CLOSE_SUCCESS_ALERT`
