export const GLOBAL_PAGE = `MOVIES_`

export const GET_MOVIES_LIST = `${GLOBAL_PAGE}GET_MOVIES_LIST`;
export const SET_MOVIES_LIST = `${GLOBAL_PAGE}SET_MOVIES_LIST`;
export const GET_MOVIE_DETAIL = `${GLOBAL_PAGE}GET_MOVIE_DETAIL`;
export const SET_MOVIE_DETAIL = `${GLOBAL_PAGE}SET_MOVIE_DETAIL`;
export const SET_LOADERS = `${GLOBAL_PAGE}SET_LOADERS`;
export const SET_MOVIE_DETAIL_DRAWER_STATE = `${GLOBAL_PAGE}SET_MOVIE_DETAIL_DRAWER_STATE`;
export const SET_SEARCH_PARAM = `${GLOBAL_PAGE}SET_SEARCH_PARAM`;